version: '3.4'

networks:
  dev-network:
    driver: bridge

services:
  tibberrobotservice:
    image: ${DOCKER_REGISTRY-}tibberrobotservice
    depends_on:
      - postgres_image
    build:
      context: .
      dockerfile: TibberRobotService/Dockerfile
    networks:
      - dev-network

  postgres_image:
    image: "postgres:15.1"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - dev-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql