version: "3.9"
services:
    postgres:
        image: "postgres:15.1"
        environment:
            - POSTGRES_PASSWORD=password       
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    dockerapi:
        image: "dockerapi1:latest"
        ports:
            - "5000:80"